# This is a basic workflow to help you get started with Actions

name: CompileResume

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: Resume.tex
          extra_fonts: |
            ./Fonts/*.ttf
            ./Fonts/*.otf
          args: -xelatex
      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: resume
          path: Resume.pdf
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: resume
          path: ./  # Download to current directory

      - name: Set up GitHub CLI
        run: sudo apt-get install -y gh
  
      - name: Set Tag with Date and Build Number
        id: date_tag
        run: |
          DATE=$(date +'%Y-%m-%d')
          TAG="${DATE}-${{ github.run_number }}"
          echo "TAG=$TAG" >> $GITHUB_ENV
  
      - name: Create Git Tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}
  

      - name: Create Release with Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ env.TAG }} --title "Release ${{ env.TAG }}" --notes "Automated release for ${{ env.TAG }}" --assets Resume.pdf
      
