# This is a basic workflow to help you get started with Actions

name: CompileResume

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: Resume.tex
          extra_fonts: |
            ./Fonts/*.ttf
            ./Fonts/*.otf
          args: -xelatex
      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: resume
          path: Resume.pdf
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Release ${{ steps.date.outputs.date }}"
          tag: ${{ steps.date.outputs.date }}

      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: resume
          path: ./  # Download to current directory

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Resume.pdf
          asset_name: Resume.pdf
          asset_content_type: application/pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: Resume.pdf
      
